### PR TITLE
Vars overridable playbook level

### PR DESCRIPTION
**Pull request by luckslovez**
I'd like to override the variables used in this particular role when invoking it from a playbook.

### CODE REVIEW

**Comment by rubenruizdegauna** [comment]
Aren't currently overridable 🤔 ? We use this role in our playbooks and we override the vars:
```
        - name: install agent via newrelic-cli
          include_role:
            name: newrelic_cli
          vars:
            repo_endpoint: "https://download.newrelic.com/"
            recipe: "newrelic-infra"
            region: "INVALID_REGION_WILL_MAKE_IT_FAIL" 
            nr_api_key: "user-api-key"
            nr_account_id: "nr-account-id"
```

**Comment by luckslovez** [comment]
> Aren't currently overridable 🤔 ? We use this role in our playbooks and we override the vars:
> 
> ```
>         - name: install agent via newrelic-cli
>           include_role:
>             name: newrelic_cli
>           vars:
>             repo_endpoint: "https://download.newrelic.com/"
>             recipe: "newrelic-infra"
>             region: "INVALID_REGION_WILL_MAKE_IT_FAIL" 
>             nr_api_key: "user-api-key"
>             nr_account_id: "nr-account-id"
> ```

When using it as `role` in `roles` vars won't get overridden;
```
- name: Install NRIA
  hosts: linux
  become: true
  gather_facts: yes
  vars:
    repo_endpoint: "https://nr-downloads-main.s3.amazonaws.com/"
    recipe: "newrelic-infra"
    region: "{{ lookup('ansible.builtin.env', 'NEW_RELIC_REGION') }}" # US | EU | STAGING
    nr_api_key: "{{ lookup('ansible.builtin.env', 'NEW_RELIC_API_KEY') }}"
    nr_account_id: "{{ lookup('ansible.builtin.env', 'NEW_RELIC_ACCOUNT_ID') }}"
  roles:
    - caos.ansible_roles.newrelic_cli
 ```

**Comment by luckslovez** [comment]
It seems like using `include_role` is able to override a role var. Playbook variables can't ovveride var roles, that is why I'd need them in `defaults/`
https://github.com/newrelic-experimental/caos-ansible-roles/pull/70#issuecomment-1968709820

>Ansible does apply variable precedence, and you might have a use for it. Here is the order of precedence from least to greatest (the last listed variables override all other variables):

image

**Comment by rubenruizdegauna** [comment]
> It seems like using `include_role` is able to override a role var. Playbook variables can't ovveride var roles, that is why I'd need them in `defaults/` [#70 (comment)](https://github.com/newrelic-experimental/caos-ansible-roles/pull/70#issuecomment-1968709820)
> 
> > Ansible does apply variable precedence, and you might have a use for it. Here is the order of precedence from least to greatest (the last listed variables override all other variables):
> 
> image

Didn't know this, thanks for the explanation :) ✅

**Review by rubenruizdegauna — APPROVED** [review]
LGTM

**Pull request merged**
